export const QUICK_VIEW_PANEL_DATA_REQUEST = 'QUICK_VIEW_PANEL_DATA_REQUEST';
export const QUICK_VIEW_PANEL_DATA_LOADED = 'QUICK_VIEW_PANEL_DATA_LOADED';
export const QUICK_VIEW_PANEL_DATA_SORTING = 'QUICK_VIEW_PANEL_DATA_SORTING';
export const QUICK_VIEW_PANEL_DATA_SORTED = 'QUICK_VIEW_PANEL_DATA_SORTED';
export const VIEW_PANEL_DATA_ERROR = 'VIEW_PANEL_DATA_ERROR';
