export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_RESULT_LOADED = 'SEARCH_RESULT_LOADED';
export const SEARCH_RESULT_SORTING = 'SEARCH_RESULT_SORTING';
export const SEARCH_RESULT_SORTED = 'SEARCH_RESULT_SORTED';
export const SEARCH_ERROR = 'SEARCH_ERROR';
