export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_RESULT_LOADED = 'SEARCH_RESULT_LOADED';

export const QUESTION_INFO_REQUEST = 'QUESTION_INFO_REQUEST';
export const QUESTION_INFO_LOADED = 'QUESTION_INFO_LOADED';

export const QUICK_VIEW_PANEL_DATA_REQUEST = ' QUICK_VIEW_PANEL_DATA_REQUEST';
export const QUICK_VIEW_PANEL_DATA_LOADED = 'QUICK_VIEW_PANEL_DATA_LOADED';
