export const SEARCH_RESULT_LOADED = 'SEARCH_RESULT_LOADED';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const QUESTION_INFO_LOADED = 'QUESTION_INFO_LOADED';
export const QUESTION_INFO_REQUEST = 'QUESTION_INFO_REQUEST';
